#!/usr/bin/env python
from __future__ import print_function

import argparse
import json
import logging
import sys
import os
import urllib
import urllib2
import base64
import collections



GROUP_KEY_ORDER = ["id", "creation_time", "name", "type", "memsize"]

def print_table(header, data):
    lengths = [0] * len(header)

    for idx, field in enumerate(header):
        maxlen = max([len(d[field[0]])+1 for d in data] + [len(field[1]) + 4])
        lengths[idx] = maxlen

    fmt = " ".join('{!s:<%d}'%l for l in lengths)

    print(fmt.format(*[c[1] for c in header]))
    for entry in data:
        print(fmt.format(*[entry[c[0]] for c in header]))

def without_http_prefix(url):
    """
    Returns a URL without the http:// or https:// prefixes
    """
    if url.startswith('http://'):
        return url[7:]
    elif url.startswith('https://'):
        return url[8:]
    return url

def http_get(url, args=None, auth=None):
    if args:
        url = url + '?' + urllib.urlencode(args, True)

    request = urllib2.Request(url)
    if auth:
        base64string = base64.encodestring(
            '%s:%s' % (auth[0], auth[1])).replace('\n', '')
        request.add_header('Authorization', 'Basic %s' % base64string)

    response = urllib2.urlopen(request)
    response_text = response.read()

    return response.getcode(), response_text

def http_post(url, data, auth=None):
    data_str = json.dumps(data)
    data_len = len(data_str)

    request = urllib2.Request(
        url,
        data_str,
        {'Content-Type': 'application/json',
         'Content-Length': data_len})

    if auth:
        base64string = base64.encodestring(
            '%s:%s' % (auth[0], auth[1])).replace('\n', '')
        request.add_header('Authorization', 'Basic %s' % base64string)

    response = urllib2.urlopen(request)
    response_text = response.read()

    return response.getcode(), response_text

def http_put(url, data, auth=None):
    data_str = json.dumps(data)
    data_len = len(data_str)

    request = urllib2.Request(
        url,
        data_str,
        {'Content-Type': 'application/json',
         'Content-Length': data_len})
    request.get_method = lambda: 'PUT'

    if auth:
        base64string = base64.encodestring(
            '%s:%s' % (auth[0], auth[1])).replace('\n', '')
        request.add_header('Authorization', 'Basic %s' % base64string)

    response = urllib2.urlopen(request)
    response_text = response.read()

    return response.getcode(), response_text

def http_delete(url, data, auth=None):
    data_str = json.dumps(data)
    data_len = len(data_str)

    request = urllib2.Request(
        url,
        data_str,
        {'Content-Type': 'application/json',
         'Content-Length': data_len})
    request.get_method = lambda: 'DELETE'

    if auth:
        base64string = base64.encodestring(
            '%s:%s' % (auth[0], auth[1])).replace('\n', '')
        request.add_header('Authorization', 'Basic %s' % base64string)

    response = urllib2.urlopen(request)
    response_text = response.read()

    return response.getcode(), response_text

def ps_command(host, is_quiet, auth):
    url = 'http://%s/api/groups' % without_http_prefix(host)

    try:
        _, data_str = http_get(url, None, auth)
    except urllib2.HTTPError, err:
        if err.code == 401:
            print("Authorization required")
            sys.exit(1)
        else:
            raise

    data = json.loads(data_str)

    result = []
    for group_id, group in data.items():
        for instance in group['instances']:

            result.append({
                'group_id': group_id,
                'instance_num': instance['name'],
                'name': group['name'],
                'type': group['type'],
                'memsize': str(group['memsize']),
                'mem_used': "{0:.3f}".format(instance['mem_used']),
                'state': group['state']['name'],
                'addr': instance['addr'],
                'host': instance['host'],
            })

    header = [
        ('group_id', 'GROUP'),
        ('instance_num', 'INSTANCE #'),
        ('name', 'NAME'),
        ('type', 'TYPE'),
        ('memsize', 'SIZE'),
        ('mem_used', 'USED'),
        ('state', 'STATE'),
        ('addr', 'ADDRESS'),
        ('host', 'NODE')
    ]

    if not is_quiet:
        print_table(header, result)
    else:
        groups = set([i['group_id'] for i in result])
        print('\n'.join(groups))


def inspect_command(host, group_id_list, auth):
    result = []
    for group_id in group_id_list:
        url = 'http://%s/api/groups/%s' % (without_http_prefix(host), group_id)
        data_str = None
        try:
            _, data_str = http_get(url, None, auth)
        except urllib2.HTTPError, err:
            if err.code == 404:
                print("No such group: '%s'" % group_id)
                sys.exit(1)
            elif err.code == 401:
                print("Authorization required")
                sys.exit(1)
            else:
                raise
        data = json.loads(data_str)

        # More important fields should be displayed on top
        ordered_data = collections.OrderedDict()
        keys = [k for k in GROUP_KEY_ORDER if k in data.keys()]
        keys = keys + [k for k in data.keys() if k not in keys]
        for key in keys:
            ordered_data[key] = data[key]
        result.append(ordered_data)
    print(json.dumps(result, indent=2))


def run_command(host, name, memsize, auth, verbose):
    args = {'name': name,
            'memsize': memsize,
            'async': True}

    url = 'http://%s/api/groups' % without_http_prefix(host)

    try:
        _, data_str = http_post(url, args, auth)
    except urllib2.HTTPError, err:
        if err.code == 401:
            print("Authorization required")
            sys.exit(1)
        else:
            raise

    data = json.loads(data_str)

    task_id = data['task_id']
    group_id = data['id']

    status = "running"
    index = 0
    while status == "running":
        url = 'http://%s/api/tasks/%s' % (without_http_prefix(host), task_id)
        args = {"index": index}
        try:
            _, data_str = http_get(url, args, auth)
        except urllib2.HTTPError, err:
            if err.code == 401:
                print("Authorization required")
                sys.exit(1)
            else:
                raise
        data = json.loads(data_str)
        index = data['index']
        status = data['status']
        for log in data['logs']:
            if verbose:
                print(log['message'])
            else:
                print('.', end='')
                sys.stdout.flush()

        if status == "error":
            print("Error: %s" % data['message'])
            sys.exit(1)

    if not verbose:
        print('')

    print(group_id)

def rm_command(host, group_id_list, auth, verbose):
    for group_id in group_id_list:
        url = 'http://%s/api/groups/%s' % (without_http_prefix(host), group_id)
        try:
            _, data_str = http_delete(url, {'async': True}, auth)
        except urllib2.HTTPError, err:
            if err.code == 404:
                print("No such group: '%s'" % group_id)
                sys.exit(1)
            elif err.code == 401:
                print("Authorization required")
                sys.exit(1)
            else:
                raise

        data = json.loads(data_str)
        task_id = data['task_id']

        status = "running"
        index = 0
        while status == "running":
            url = 'http://%s/api/tasks/%s' % (without_http_prefix(host), task_id)
            args = {"index": index}
            try:
                _, data_str = http_get(url, args, auth)
            except urllib2.HTTPError, err:
                if err.code == 401:
                    print("Authorization required")
                    sys.exit(1)
                else:
                    raise
            data = json.loads(data_str)
            index = data['index']
            status = data['status']
            for log in data['logs']:
                if verbose:
                    print(log['message'])
                else:
                    print('.', end='')
                    sys.stdout.flush()

            if status == "error":
                print("Error: %s" % data['message'])
                sys.exit(1)

    if not verbose:
        print('')


def update_command(host, group_id, name, memsize, auth, verbose):
    data = {'async': True}
    if name:
        data['name'] = name
    if memsize:
        data['memsize'] = memsize

    url = 'http://%s/api/groups/%s' % (without_http_prefix(host), group_id)

    try:
        _, data_str = http_put(url, data, auth)
    except urllib2.HTTPError, err:
        if err.code == 404:
            print("No such group: '%s'" % group_id)
            sys.exit(1)
        elif err.code == 401:
            print("Authorization required")
            sys.exit(1)
        else:
            raise

    data = json.loads(data_str)
    task_id = data['task_id']

    status = "running"
    index = 0
    while status == "running":
        url = 'http://%s/api/tasks/%s' % (without_http_prefix(host), task_id)
        args = {"index": index}
        try:
            _, data_str = http_get(url, args, auth)
        except urllib2.HTTPError, err:
            if err.code == 401:
                print("Authorization required")
                sys.exit(1)
            else:
                raise
        data = json.loads(data_str)
        index = data['index']
        status = data['status']
        for log in data['logs']:
            if verbose:
                print(log['message'])
            else:
                print('.', end='')
                sys.stdout.flush()

        if status == "error":
            print("Error: %s" % data['message'])
            sys.exit(1)

    if not verbose:
        print('')

def upgrade_command(host, group_id, auth, verbose):
    data = {'async': True,
            'docker_image_name': 'tarantool-cloud-memcached'}

    url = 'http://%s/api/groups/%s' % (without_http_prefix(host), group_id)

    try:
        _, data_str = http_put(url, data, auth)
    except urllib2.HTTPError, err:
        if err.code == 404:
            print("No such group: '%s'" % group_id)
            sys.exit(1)
        elif err.code == 401:
            print("Authorization required")
            sys.exit(1)
        else:
            raise

    data = json.loads(data_str)
    task_id = data['task_id']

    status = "running"
    index = 0
    while status == "running":
        url = 'http://%s/api/tasks/%s' % (without_http_prefix(host), task_id)
        args = {"index": index}
        try:
            _, data_str = http_get(url, args, auth)
        except urllib2.HTTPError, err:
            if err.code == 401:
                print("Authorization required")
                sys.exit(1)
            else:
                raise
        data = json.loads(data_str)
        index = data['index']
        status = data['status']
        for log in data['logs']:
            if verbose:
                print(log['message'])
            else:
                print('.', end='')
                sys.stdout.flush()

        if status == "error":
            print("Error: %s" % data['message'])
            sys.exit(1)

    if not verbose:
        print('')



def main():
    # Don't spam with HTTP connection logs from 'requests' module
    logging.getLogger("requests").setLevel(logging.WARNING)

    parser = argparse.ArgumentParser()

    parser.add_argument('-H', '--host',
                        default = None,
                        help='specify taas host to connect to')

    parser.add_argument('-v', '--verbose',
                        action='store_true',
                        default=False,
                        help='enable verbose output')

    parser.add_argument('-u', '--username',
                        help='User name for HTTP Basic Auth')

    parser.add_argument('-p', '--password',
                        help='Password for HTTP Basic Auth')

    subparsers = parser.add_subparsers(title="commands", dest="subparser_name")

    ps_parser = subparsers.add_parser(
        'ps', help='show a list of running groups')
    ps_parser.add_argument(
        '-q', '--quiet',
        action='store_true',
        help='only show group IDs')

    inspect_parser = subparsers.add_parser(
        'inspect', help='inspect a group')
    inspect_parser.add_argument(
        'group_id',
        nargs='+',
        help='group to inspect')

    run_parser = subparsers.add_parser(
        'run', help='run a new group')
    run_parser.add_argument(
        '--name',
        help='name of the new group')
    run_parser.add_argument(
        'memsize',
        type=float,
        help='amount of memory to allocate, in GiB (default is 0.5)',
        nargs='?',
        default=0.5)

    rm_parser = subparsers.add_parser(
        'rm', help='remove one or more groups')
    rm_parser.add_argument(
        'group_id',
        nargs='+',
        help='group to remove')

    update_parser = subparsers.add_parser(
        'update', help='update an existing group')
    update_parser.add_argument('--memsize',
                               type=float,
                               help='amount of memory to set',
                               default=None)
    update_parser.add_argument('--name',
                               help='name to set',
                               default=None)
    update_parser.add_argument('group_id',
                               help='group ID to update')

    upgrade_parser = subparsers.add_parser(
        'upgrade', help='upgrade an existing group')
    upgrade_parser.add_argument('group_id',
                                help='group ID to upgrade')

    args = parser.parse_args()

    auth = None
    if args.username and args.password:
        auth = (args.username, args.password)

    host = None
    if args.host is None:
        if 'TARANTOOL_CLOUD_HOST' in os.environ:
            host = os.environ['TARANTOOL_CLOUD_HOST']
        else:
            sys.exit("Please specify --host or pass TARANTOOL_CLOUD_HOST via env")
    else:
        host = args.host

    if args.subparser_name == 'ps':
        ps_command(host, args.quiet, auth)
    if args.subparser_name == 'inspect':
        inspect_command(host, args.group_id, auth)
    elif args.subparser_name == 'run':
        run_command(host, args.name, args.memsize, auth, args.verbose)
    elif args.subparser_name == 'rm':
        rm_command(host, args.group_id, auth, args.verbose)
    elif args.subparser_name == 'update':
        update_command(host, args.group_id, args.name,
                       args.memsize, auth, args.verbose)
    elif args.subparser_name == 'upgrade':
        upgrade_command(host, args.group_id, auth, args.verbose)


if __name__ == '__main__':
    main()
